//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSmartKitchen.Models
{
    using System;
    using System.Linq;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;
    using System.Threading.Tasks;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }

        // To override SaveChanges
        // http://devillers.nl/improving-dbentityvalidationexception/
        public override async Task<int> SaveChangesAsync()
        {
            try
            {
                return await base.SaveChangesAsync();
            }
            catch (DbEntityValidationException ex)
            {
                // Retrieve the error messages as a list of strings.
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                // Join the list to a single string.
                var fullErrorMessage = string.Join("; ", errorMessages);

                // Combine the original exception message with the new one.
                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                // Throw a new DbEntityValidationException with the improved exception message.
                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
        }
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devices> DevicesSet { get; set; }
        public virtual DbSet<Exercises> ExercisesSet { get; set; }
        public virtual DbSet<Kitchen> KitchenSet { get; set; }
        public virtual DbSet<ShoppingBags> ShoppingBagsSet { get; set; }
        public virtual DbSet<ShoppingBagProducts> ShoppingBagProductsSet { get; set; }
        public virtual DbSet<Members> MembersSet { get; set; }
        public virtual DbSet<MemberLength> MemberLengthSet { get; set; }
        public virtual DbSet<MemberWeight> MemberWeightSet { get; set; }
        public virtual DbSet<ProductsFridge> ProductsFridgeSet { get; set; }
    }
}
