//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSmartKitchen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devices> DevicesSet { get; set; }
        public virtual DbSet<Exercises> ExercisesSet { get; set; }
        public virtual DbSet<Kitchen> KitchenSet { get; set; }
        public virtual DbSet<ShoppingBags> ShoppingBagsSet { get; set; }
        public virtual DbSet<ShoppingBagProducts> ShoppingBagProductsSet { get; set; }
        public virtual DbSet<Members> MembersSet { get; set; }
        public virtual DbSet<MemberLength> MemberLengthSet { get; set; }
        public virtual DbSet<MemberWeight> MemberWeightSet { get; set; }
        public virtual DbSet<ProductsFridge> ProductsFridgeSet { get; set; }
    }
}
