//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitchen_WebService_OAMK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int idKitchen { get; set; }
    
        public virtual Kitchen Kitchen { get; set; }
    }
}
