//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitchen_WebService_OAMK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen
    {
        public Kitchen()
        {
            this.Devices = new HashSet<Devices>();
            this.Members1 = new HashSet<Members>();
            this.ProductsFridge = new HashSet<ProductsFridge>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int adminID { get; set; }
        public Nullable<int> shoppingBagID { get; set; }
        public string temperatureFridge { get; set; }
    
        public virtual ICollection<Devices> Devices { get; set; }
        public virtual Members Members { get; set; }
        public virtual ICollection<Members> Members1 { get; set; }
        public virtual ICollection<ProductsFridge> ProductsFridge { get; set; }
        public virtual ShoppingBags ShoppingBags { get; set; }
    }
}
