//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitchen_WebService_OAMK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Kitchen = new HashSet<Kitchen>();
            this.MemberLength = new HashSet<MemberLength>();
            this.ShoppingBagProducts = new HashSet<ShoppingBagProducts>();
            this.MemberWeight = new HashSet<MemberWeight>();
            this.ProductsFridge = new HashSet<ProductsFridge>();
        }
    
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int dateOfBirth { get; set; }
        public string email { get; set; }
        public string pictureUrl { get; set; }
        public string defaultColor { get; set; }
        public string gameActivated { get; set; }
        public Nullable<int> gameHealthLevel { get; set; }
        public Nullable<int> gamePoints { get; set; }
        public string password { get; set; }
        public int idKitchen { get; set; }
    
        public virtual ICollection<Kitchen> Kitchen { get; set; }
        public virtual Kitchen Kitchen1 { get; set; }
        public virtual ICollection<MemberLength> MemberLength { get; set; }
        public virtual ICollection<ShoppingBagProducts> ShoppingBagProducts { get; set; }
        public virtual ICollection<MemberWeight> MemberWeight { get; set; }
        public virtual ICollection<ProductsFridge> ProductsFridge { get; set; }
    }
}
