//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitchen_WebService_OAMK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsFridge
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string idNFC { get; set; }
        public string category { get; set; }
        public Nullable<int> calories { get; set; }
        public string address { get; set; }
        public string quantity { get; set; }
        public string expirationDate { get; set; }
        public string available { get; set; }
        public int kitchenID { get; set; }
        public Nullable<int> addedBy { get; set; }
    
        public virtual Kitchen Kitchen { get; set; }
        public virtual Members Members { get; set; }
    }
}
