//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitchen_WebService_OAMK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingBagProducts
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string quantity { get; set; }
        public string category { get; set; }
        public string shop { get; set; }
        public int addedBy { get; set; }
        public int shoppingBagID { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual ShoppingBags ShoppingBags { get; set; }
    }
}
