//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSmartKitchen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen
    {
        public Kitchen()
        {
            this.ShoppingBags = new HashSet<ShoppingBags>();
            this.Devices = new HashSet<Devices>();
            this.ProductsFridge = new HashSet<ProductsFridge>();
            this.Members = new HashSet<Members>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TemperatureFridge { get; set; }
    
        public virtual ICollection<ShoppingBags> ShoppingBags { get; set; }
        public virtual ICollection<Devices> Devices { get; set; }
        public virtual ICollection<ProductsFridge> ProductsFridge { get; set; }
        public virtual ICollection<Members> Members { get; set; }
    }
}
