//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSmartKitchen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberWeight
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public string Date { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
